version: '3'

services:
  zeppelin:
    build: .
    restart: always
    ports:
      - "9999:8080"
    volumes: 
      - ./logs:/opt/zeppelin/logs
      - ./notebook:/opt/zeppelin/notebook
      - ./conf:/opt/zeppelin/conf
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      TZ: Asia/Seoul




