version: '3'

services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    restart: always
    ports:
      - "9999:8080"
    volumes: 
      - ./logs:/opt/zeppelin/logs
      - ./notebook:/opt/zeppelin/notebook
      - ./conf:/opt/zeppelin/conf

    # environment:
    #   - ZEPPELIN_LOG_DIR=/zeppelin/logs
    #   - ZEPPELIN_NOTEBOOK_DIR=/zeppelin/notebook


